// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.920
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Aftercare() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<article class=\"aftercare-content w-full max-w-2xl mx-auto px-6 py-8 sm:px-4 sm:py-12\"><h1 class=\"aftercare-title text-2xl sm:text-3xl font-semibold tracking-tight text-center mb-8\">Tattoo aftercare instructions</h1><div class=\"aftercare-body text-lg space-y-8\"><section><ul class=\"aftercare-list space-y-3\"><li>Keep the bandage on for 2–3 days.</li><li>Do not swim, get sunburned, or sweat.</li><li>After 3 days, take off the bandage in the shower.</li><li>Pat dry with a clean paper towel (do not rub).</li><li>Let it air out for about 10 minutes, then apply a thin layer of Aquaphor or a recommended tattoo ointment.</li><li>Continue applying a thin layer of Aquaphor or tattoo healing ointment 2 times a day (thin layer only).</li><li>Do not over-moisturize—your skin needs to breathe.</li></ul></section><section><h2 class=\"aftercare-heading font-semibold text-xl mb-3\">Days 5–14</h2><ul class=\"aftercare-list space-y-3\"><li>Tattoo may start to peel or flake—this is normal. Do not pick or scratch.</li><li>Switch to a fragrance-free lotion like Aveeno or Lubriderm instead of Aquaphor.</li><li>Keep moisturizing to prevent excessive itching or scabbing.</li></ul></section><section class=\"aftercare-avoid\"><h2 class=\"aftercare-heading font-semibold text-xl mb-3\">Avoid</h2><ul class=\"aftercare-list space-y-3\"><li>No swimming, saunas, or soaking (including baths) for at least 2 weeks.</li><li>No direct sunlight or tanning on the tattoo until fully healed.</li><li>No tight clothing rubbing against the tattoo.</li><li>Do not apply alcohol, peroxide, Vaseline, or scented products.</li></ul></section><section class=\"aftercare-tips\"><h2 class=\"aftercare-heading font-semibold text-xl mb-3\">Tips</h2><ul class=\"aftercare-list space-y-3\"><li>Healing usually takes 2–4 weeks, depending on your skin and tattoo size.</li></ul></section></div></article>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Page("Tattoo Aftercare | tat.it.too", "Tattoo aftercare instructions. How to care for your new tattoo. Keep it clean and heal well.", "https://www.tatit2.com/aftercare.html", "https://www.tatit2.com/aftercare.html").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
