// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.920
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Book() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<script>\n        document.addEventListener('DOMContentLoaded', function() {\n            const form = document.getElementById(\"booking-form\");\n            form.addEventListener('submit', function(event) {\n                event.preventDefault();\n                window.location.href = `mailto:tatittoo.a@gmail.com?subject=Booking Request [${form.name.value}]&body=` + \n                    encodeURIComponent(\"Name: \" + form.name.value + \"\\n\" +\n                                       \"Email: \" + form.email.value + \"\\n\" +\n                                       \"Phone Number: \" + form.number.value + \"\\n\" +\n                                       \"Description: \" + form.description.value),true;\n                console.log(\"Booking request sent!\");\n            });\n        });\n    </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"card w-full h-full\"><div class=\"card-body items-center\"><form id=\"booking-form\"><fieldset class=\"fieldset\"><legend class=\"fieldset-legend\">Name</legend> <input autocomplete=\"name\" name=\"name\" type=\"text\" class=\"input validator border min-w-200\" required></fieldset><fieldset class=\"fieldset\"><legend class=\"fieldset-legend\">Email</legend> <input autocomplete=\"email\" name=\"email\" type=\"email\" pattern=\"[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,4}$\" class=\"input validator border min-w-200\" required></fieldset><fieldset class=\"fieldset\"><legend class=\"fieldset-legend\">Phone Number</legend> <input autocomplete=\"tel\" name=\"number\" type=\"tel\" class=\"input validator border min-w-200\" required></fieldset><fieldset class=\"fieldset\"><legend class=\"fieldset-legend\">Description</legend> <textarea autocomplete=\"off\" name=\"description\" class=\"textarea h-24 validator border min-w-200\" placeholder=\"Your tattoo description\" required></textarea></fieldset><fieldset class=\"fieldset\"><button type=\"submit\" class=\"hover:bg-black hover:text-white justify-center w-50 input border\">Submit</button></fieldset></form></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Page().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
