// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.920
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func FineLine() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"grid min-h-full place-items-center bg-white px-4 py-12 sm:py-16 lg:px-6\" role=\"region\" aria-labelledby=\"fine-line-heading\"><div class=\"text-center\"><h1 id=\"fine-line-heading\" class=\"text-2xl font-bold text-center mb-6\">REALISM &amp; FINE LINE INFORMATION</h1><p class=\"text-center mb-4\">Please send me all information below.<br></p><ul class=\"list-disc list-inside space-y-2\"><li><span class=\"font-semibold\">Full Name</span></li><li><span class=\"font-semibold\">Photo references</span><br><span class=\"text-md\">If you have any reference photos of a tattoo reference, feel free to send it.</span></li><li><span class=\"font-semibold\">The placement picture on your body</span><br><span class=\"text-md\">Please attach a picture of your body for context around the area.</span></li><li><span class=\"font-semibold\">Size (inches)</span><br><span class=\"text-md\">Inches only please, not centimeters.</span></li><li><span class=\"font-semibold\">Color (or black and grey)</span></li></ul><p class=\"mt-6\">If you have any questions or need more details, feel free to let me know.</p><p class=\"mt-2\">I will get back to you <span class=\"font-semibold\">as soon as possible.</span></p><p class=\"mt-4 text-center font-medium\">Thank you for your patience 🖤</p></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Page("tat.it.too – Tattoo Artist | Book Online", "tat.it.too – Custom tattoos and flash. Book your appointment online.", "", "https://www.tatit2.com/").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
