// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.920
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "time"

// border-b
func Page() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><title>tat.it.too</title><link rel=\"icon\" href=\"images/favicon.webp\" type=\"image/webp\"><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><link type=\"text/css\" href=\"./src/tailwind.css\" rel=\"stylesheet\"><link type=\"text/css\" href=\"./src/main.css\" rel=\"stylesheet\"><link rel=\"preconnect\" href=\"https://fonts.googleapis.com\"><link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin><link href=\"https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800&display=swap\" rel=\"stylesheet\" async defer><link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=EB+Garamond\" async defer><script>\n\t\t\t\tdocument.addEventListener('DOMContentLoaded', function() {\n\t\t\t\t\tlet path = window.location.href;\n\t\t\t\t\t// Strip the prefix and get the last part of the URL\n\t\t\t\t\t// foo.com/bar/baz.html -> baz.html\n\t\t\t\t\tpath = path.substring(path.lastIndexOf('/')+1);\n\t\t\t\t\tdocument.getElementById(path).classList.add('border-b');\n\t\t\t\t});\n\t\t\t</script></head><body><div class=\"navbar p-0\"><div class=\"navbar-start md:flex\"><img src=\"images/favicon.webp\" alt=\"tat.it.too logo\" class=\"w-16 h-16 rounded-full\"></div><div class=\"navbar-center md:flex\"><ul class=\"menu menu-horizontal text-2xl p-0\"><li id=\"index.html\"><a href=\"index.html\">Home</a></li><li id=\"fine_line.html\"><a href=\"fine_line.html\">Fine Line</a></li><li id=\"pet_portraits.html\"><a href=\"pet_portraits.html\">Pet Portraits</a></li><li id=\"book.html\"><a href=\"book.html\">Book</a></li><li><a href=\"https://www.instagram.com/tat.it.too/\">Instagram</a></li></ul></div><div class=\"navbar-end md:flex\"></div></div><div class=\"card w-full h-full\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><hr class=\"h-px my-1 bg-gray-200 border-0 dark:bg-gray-700 mx-3\"><footer class=\"footer sm:footer-horizontal footer-end p-4 justify-end\"><aside><p>Copyright © ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(time.Now().Format("2006"))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `page.templ`, Line: 52, Col: 48}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " - All right reserved</p></aside></footer></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
