#!/usr/bin/env python3
"""Generate responsive webp variants next to the originals and write imagemeta_gen.go.
Run from the repo root: python3 scripts/images.py (also run by `task images`)."""
import os, glob
from PIL import Image
PLAN = {
  'images/work/*.webp':   [240, 480, 800, 1200, 1600, 2400],
  'images/art/angel-and-demon.webp': [480, 800, 1600],
  'images/art/butterfly.webp': [480],
  'images/artist.webp':   [300, 600],
  'images/flash/*.webp':  [400, 800],
}
ALL = sum(PLAN.values(), [])
meta = {}
for pat, widths in PLAN.items():
    for src in sorted(glob.glob(pat)):
        base, _ = os.path.splitext(src)
        if any(base.endswith('-%d' % w) for w in ALL):
            continue
        im = Image.open(src); W, H = im.size
        avail = []
        for w in widths:
            if w >= W:
                continue
            out = f'{base}-{w}.webp'
            if not os.path.exists(out):
                r = im.copy(); r.thumbnail((w, 100000), Image.LANCZOS); r.save(out, 'WEBP', quality=80, method=6)
            avail.append(w)
        meta[src] = (W, H, avail)
lines = ['// Code generated by scripts/images.py; DO NOT EDIT.', '', 'package main', '', 'var imageMeta = map[string]imageInfo{']
for k in sorted(meta):
    W, H, avail = meta[k]
    lines.append('\t"%s": {%d, %d, []int{%s}},' % (k, W, H, ', '.join(map(str, avail))))
lines.append('}')
open('imagemeta_gen.go', 'w').write('\n'.join(lines) + '\n')
print('ok', len(meta), 'images')
